# -*- coding: utf-8 -*-
"""WiDS_Week2_Day1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HF1pPSr3toH-BSdRXOOrcWtjEH-tpJkW
"""

import heapq

class Order:
  def __init__(self, order_id, side, price, qty, timestamp, order_type="limit"):
    self.id = order_id
    self.side = side
    self.price = price
    self.qty = qty
    self.initial_qty = qty
    self.ts = timestamp
    self.type = order_type
    self.status = "NEW"

  def __repr__(self):
    return(
        f"Order(id={self.id}, side={self.side}, price={self.price}), qty={self.qty}, status={self.status}"
    )

class OrderBook:
  def __init__(self):
    self.bids = []
    self.asks = []

  def best_bid(self):
    if not self.bids:
      return None
    return -self.bids[0][0]

  def best_ask(self):
    if not self.asks:
      return None
    return self.asks[0][0]

  def add_limit(self, order):
    if order.side == "buy":
      heapq.heappush(self.bids, (-order.price, order.ts, order))
    else:
      heapq.heappush(self.asks, (order.price, order.ts, order))

    self.match()

  def match(self):
    while self.bids and self.asks:
      best_bid_price = -self.bids[0][0]
      best_ask_price = self.asks[0][0]

      if best_bid_price < best_ask_price:
        break

      _, _, buy_order = heapq.heappop(self.bids)
      _, _, sell_order = heapq.heappop(self.asks)

      trade_qty = min(buy_order.qty, sell_order.qty)

      buy_order.qty -= trade_qty
      sell_order.qty -= trade_qty

      print(f"TRADE {trade_qty} @ {best_ask_price}")

      buy_order.status = (
          "FILLED" if buy_order.qty == 0 else "PARTIALLY_FILLED"
      )
      sell_order.status = (
          "FILLED" if sell_order.qty == 0 else "PARTIALLY_FILLED"
      )

      if buy_order.qty > 0:
        heapq.heappush(
            self.bids, (-buy_order.price, buy_order.ts, buy_order)
        )
      if sell_order.qty > 0:
        heapq.heappush(
            self.asks, (sell_order.price, sell_order.ts, sell_order)
        )

book = OrderBook()

orders = [
    Order(1, "buy", 100, 10, 1),
    Order(2, "buy", 101, 5, 2),
    Order(3, "sell", 102, 7, 3),
    Order(4, "sell", 101, 4, 4)
]

for o in orders:
  book.add_limit(o)

print("Best Bid: ", book.best_bid())
print("Best Ask: ", book.best_ask())