# -*- coding: utf-8 -*-
"""WiDS_Week2_Day1_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p98Bk99heW1PiYLxhjtyT-4-3W7LaLEz
"""

import random
import time
from bisect import bisect_left
import heapq

def generate_orders(n):
  return [random.randint(90, 110) for _ in range(n)]

def list_insertion(prices):
  book = []
  start = time.time()
  for p in prices:
    idx = bisect_left(book, p)
    book.insert(idx, p)
  return time.time() - start

def heap_intersection(prices):
  heap = []
  start = time.time()
  for p in prices:
    heapq.heappush(heap, p)
  return time.time() - start

random.seed(42)
prices = generate_orders(10_000)

print("List time:", list_insertion(prices))
print("Heap time:", heap_intersection(prices))