# -*- coding: utf-8 -*-
"""Week0_Day2_WiDS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OZDysdc5QGkZoM1trXXM5XrgDDBqpXcb
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

file_id = '1dPnyCnPaeo5EmnFUIletgPXNtbeei1Hi'
url = f'https://drive.google.com/uc?id={file_id}'
df = pd.read_csv(url)
display(df.head())
df.info()

df = df.reset_index(drop=True)

if isinstance(df.columns[0], tuple):
  df.columns = [c[0] for c in df.columns]

df.head()

df['date'] = pd.to_datetime(df['date'])
df.set_index('date', inplace=True)

df = df.sort_index()

df_daily = df['close'].resample('D').last()
df_daily = df_daily.dropna()
display(df_daily.head())

df_daily = df_daily.to_frame()
df_daily['Daily Returns'] = df_daily['close'].pct_change()

df_daily['20D Volatility'] = df_daily['Daily Returns'].rolling(window=20).std()
display(df_daily.head())

plt.figure(figsize=(14,7))
plt.plot(df_daily['20D Volatility'])
plt.title('20-Day Rolling Volatility')
plt.xlabel('Date')
plt.ylabel('Price/Volatility')
plt.grid(True)
plt.show()

plt.figure(figsize=(10,5))
sns.histplot(df_daily['Daily Returns'].dropna(), bins=50, kde=True)
plt.title("Histogram of Daily Returns of NIFTY 50")
plt.xlabel("Returns")
plt.ylabel("Frequency")
plt.show()