# -*- coding: utf-8 -*-
"""Week0_Report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PkF5G1KEv03AbBxagT63ZYIu4fvjbpfi
"""

import numpy as np
import matplotlib.pyplot as plt

def gbm_simulate_paths(S0, mu, sigma, T, dt, n_paths):
  N = int(T / dt)
  t = np.linspace(0, T, N)

  paths = np.zeros((n_paths, N))
  paths[:, 0] = S0

  for i in range(n_paths):
    Z = np.random.standard_normal(N - 1)
    W = np.cumsum(Z) * np.sqrt(dt)
    X = (mu - 0.5 * sigma**2) * t[1:] + sigma * W
    paths[i, 1:] = S0 * np.exp(X)

  return t, paths

S0 = 100
mu = 0.10
sigma = 0.20
T = 1
dt = 1/252
n_paths = 20

t, paths = gbm_simulate_paths(S0, mu, sigma, T, dt, n_paths)

plt.figure(figsize=(10,6))
for i in range(n_paths):
  plt.plot(t, paths[i], linewidth=1)
plt.title("GBM Simulated Stock Price Paths")
plt.xlabel("Time (years)")
plt.ylabel("Price")
plt.grid(True)
plt.show()

def call_option(S0, K, r, sigma, T, N=10000):
  Z = np.random.standard_normal(N)
  ST = S0 * np.exp((r - 0.5*sigma**2)*T + sigma*np.sqrt(T)*Z)
  payoff = np.maximum(ST - K, 0)
  return np.exp(-r*T) * payoff.mean()

def put_option(S0, K, r, sigma, T, N=10000):
  Z = np.random.standard_normal(N)
  ST = S0 * np.exp((r - 0.5*sigma**2)*T + sigma*np.sqrt(T)*Z)
  payoff = np.maximum(K - ST, 0)
  return np.exp(-r*T) * payoff.mean()

K = 100
r = 0.05
N = 20000

call_price = call_option(S0, K, r, sigma, T, N)
put_price = put_option(S0, K, r, sigma, T, N)

print("Monte Carlo Call Price: ", call_price)
print("Monte Carlo Put Price: ", put_price)

ST = np.linspace(50, 150, 500)
call_payoff = np.maximum(ST - K, 0)
put_payoff = np.maximum(K - ST, 0)

plt.figure(figsize=(8,5))
plt.plot(ST, call_payoff)
plt.axvline(K, color='red', linestyle='--')
plt.title("Call Option Payoff at Expiry")
plt.xlabel("Stock Price at Expiry (ST)")
plt.ylabel("Payoff")
plt.grid(True)
plt.show()

plt.figure(figsize=(8,5))
plt.plot(ST, put_payoff)
plt.axvline(K, color='red', linestyle='--')
plt.title("Put Option Payoff at Expiry")
plt.xlabel("Stock Price at Expiry (ST)")
plt.ylabel("Payoff")
plt.grid(True)
plt.show()