# -*- coding: utf-8 -*-
"""Week0_Day3_WiDS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17iCM7I659NhaC3A1e1SgSmjKk-UDl_5n
"""

import numpy as np
import matplotlib.pyplot as plt

def GeneratePathsGBMABM(NoOfPaths, NoOfSteps, T, mu, sigma, S_0, seed=1):
  #X_{t+1} = X_{t} + (mu - 0.5*sigma^2)*dt + sigma*sqrt(dt)*Z_t
  #X_{t} = ln(S_{t})

  np.random.seed(seed)

  Z = np.random.normal(0.0, 1.0, [NoOfPaths, NoOfSteps])

  X = np.zeros([NoOfPaths, NoOfSteps + 1])
  S = np.zeros([NoOfPaths, NoOfSteps + 1])
  time = np.zeros([NoOfSteps + 1])

  X[:, 0] = np.log(S_0)

  dt = T / float(NoOfSteps)

  for i in range(NoOfSteps):
    if NoOfPaths > 1:
      Z[:, i] = (Z[:, i] - np.mean(Z[:, i]) / np.std(Z[:, i]))

    X[:, i+1] = X[:, i] + (mu - 0.5*sigma**2) * dt + sigma * np.sqrt(dt) * Z[:, i]
    time[i+1] = time[i] + dt

  S = np.exp(X)

  paths = {"time": time, "X": X, "S": S}
  return paths

def mainCalculation():
  NoOfPaths = 10
  NoOfSteps = 252
  T = 1.0
  mu = 0.08
  sigma = 0.20
  S_0 = 100.0
  seed = 42

  Paths = GeneratePathsGBMABM(NoOfPaths, NoOfSteps, T, mu, sigma, S_0, seed=seed)
  timeGrid = Paths["time"]
  X = Paths["X"]
  S = Paths["S"]

  plt.figure(figsize=(10,4))
  for i in range(NoOfPaths):
    plt.plot(timeGrid, S[i, :], lw=1.2)
  plt.grid(True)
  plt.xlabel("time (years)")
  plt.ylabel("S(t)")
  plt.title(f"Price paths (N={NoOfPaths}, S0={S_0}, mu={mu}, sigma={sigma})")
  plt.show()

  final_prices = S[:, -1]
  plt.figure(figsize=(8,4))
  plt.hist(final_prices, bins=max(6, NoOfPaths//2), edgecolor="k", alpha=0.7)
  plt.grid(axis='y', alpha=0.6)
  plt.xlabel("Final Price S(T)")
  plt.ylabel("Frequency")
  plt.title("Histogram of Final Prices")
  plt.show()


mainCalculation()