# -*- coding: utf-8 -*-
"""Week0_Day1_WiDS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFnnhmKsjzyiHhWaW0qDwjkggUWfWjlG
"""

import pandas as pd
import matplotlib.pyplot as plt

file_id = '19KMBXZq_WZ6NFMTC1KHFBFfzyC25cgy8'
url = f'https://drive.google.com/uc?id={file_id}'
df = pd.read_csv(url)
display(df.head())
df.info()

df['Close/Last'] = df['Close/Last'].str.replace('$', '', regex=False).astype(float)

df = df.reset_index()

if isinstance(df.columns[0], tuple):
  df.coulmns = [c[0] for c in df.columns]

df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace=True)
df['Daily Returns'] = df['Close/Last'].pct_change()
df['20-Day SMA'] = df['Close/Last'].rolling(window=20).mean()
display(df.head())

plt.figure(figsize=(14,7))
plt.plot(df['Close/Last'], label='Closing Price', color='blue')
plt.plot(df['20-Day SMA'], label='20-Day SMA', color='red', linestyle='--')

plt.title('AAPL Closing Price and 20-Day Simple Moving Average')
plt.xlabel('Date')
plt.ylabel('Price (USD)')

plt.legend()
plt.grid(True)
plt.show()